export type TransactionEth = {
    blockHash: string,
    blockNumber: string,
    from: string,
    gas: string,
    gasPrice: string,
    hash: string,
    input: string,
    nonce: string,
    r: string,
    s: string,
    to: string,
    transactionIndex: string,
    v: string,
    value: string,
}
