name: Test

on: [pull_request]

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: yarn install
              env:
                  PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
              run: |
                  yarn install --frozen-lockfile --network-timeout 300000

            - name: yarn bootstrap
              env:
                  PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
              run: |
                  yarn run bootstrap

            - name: yarn lint
              env:
                  PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
              run: |
                  yarn lint
            - name: yarn test
              env:
                  PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
              run: |
                  yarn test
            - uses: codecov/codecov-action@v2
              with:
                token: ${{ secrets.CODECOV_TOKEN_CORE }} # not required for public repos
                files: ${{github.workspace}}/packages/swapper-elements/coverage/lcov.info,${{github.workspace}}/packages/swapper-components/coverage/lcov.info,${{github.workspace}}/packages/swapper-wallets/coverage/lcov.info # optional
                flags: swapper-elements # optional
                name: codecov swapper-elements # optional
                fail_ci_if_error: true # optional (default = false)
                verbose: true # optional (default = false)